language: cpp

compiler:
    - gcc
    - clang

install:
    - git clone git@github.com:ESROCOS/tools-cmake.git
    - cd tools-cmake

script:
    - mkdir build && cd build/
    - cmake ..
    - make
    - make test

notifications:
    email:
        - havyhidalgo@gmail.com


