language: cpp

compiler:
    - gcc
    - clang

install:
    - git clone https://github.com/ESROCOS/tools-cmake.git
    - cd tools-cmake
    - mkdir build && cd build/
    - cmake ..
    - make && make install
    - sudo make install
    - cd ../../

script:
    - mkdir build && cd build/
    - cmake ..
    - make
    - make test

notifications:
    email:
        - havyhidalgo@gmail.com


