language: cpp

os: linux

dist: trusty

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-7
        - g++-7
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-3.4
        - g++-3.4
    apt:
      sources:
        - llvm-toolchain-trusty-4.0
      packages:
        - clang-4.0
        - libc++-dev

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libeigen3-dev

install:
    # esrocos cmake
    - git clone https://github.com/ESROCOS/tools-cmake.git
    - cd tools-cmake
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

    # rock cmake
    - git clone https://github.com/rock-core/base-cmake.git
    - cd base-cmake
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../


    # rock logging
    - git clone https://github.com/rock-core/base-logging.git
    - cd base-logging
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

    # SISL library
    - git clone https://github.com/SINTEF-Geometry/SISL.git base-sisl
    - cd base-sisl
    - git checkout SISL_4_5_0
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

    # esrocos types
    - git clone https://github.com/jhidalgocarrio/base-types.git
    - cd base-types
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

script:
    - mkdir build && cd build/
    - cmake ..
    - make
    - make test

notifications:
    email:
        - havyhidalgo@gmail.com
