language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libeigen3-dev

install:
    # esrocos cmake
    - git clone https://github.com/ESROCOS/tools-cmake.git
    - cd tools-cmake
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

    # rock cmake
    - git clone https://github.com/rock-core/base-cmake.git
    - cd base-cmake
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../


    # rock logging
    - git clone https://github.com/rock-core/base-logging.git
    - cd base-logging
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

    # esrocos types
    - git clone https://github.com/jhidalgocarrio/base-types.git
    - cd base-types
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../
    - git clone https://github.com/jhidalgocarrio/base-types.git
    - cd base-types
    - mkdir build && cd build/
    - cmake ..
    - make
    - sudo make install
    - cd ../../

script:
    - mkdir build && cd build/
    - cmake ..
    - make
    - make test

notifications:
    email:
        - havyhidalgo@gmail.com
